### ISSUE TITLE
Error reported when calling ClaimRewards

### ISSUE THREAD

**Issue by LINJINTIANDE** [CESSProject/cess-go-sdk#194]
I use the QueryRewards method to check if there are rewards, but calling the ClaimRewards method fails because: noSminer.Receiveevent is found, and returns (hash0xcaca6e5e1446dd8310f0995b2ae7abe24765551b7fee05925a885e8b8ef00a3a). In the browser I found the information that I had received the reward [https://substats.cess.cloud/transfer/0xfc53b94125fde43671ebfab17ef1afec6c254491e74f263840616369fe759883](https://substats.cess.cloud/transfer/0xfc53b94125fde43671ebfab17ef1afec6c254491e74f263840616369fe759883). Uplinking was successful but the information returned by the sdk reported an error.

**Comment by AstaFrode** [comment]
@LINJINTIANDE The reason for this problem is that go sdk determines success based on the Sminer.ReceiveReward event, but this transaction did not report the event. We will fix this problem.

**Comment by LINJINTIANDE** [comment]
🙏
