### ISSUE TITLE
当 `cli.Register` 失败时，返回更有用的错误信息

### ISSUE THREAD

**Issue by jimmychu0807** [CESSProject/cess-go-sdk#90]
在跑 `TestRegisterDeOSS` 测试用例时，错误时只返回 `empty` 的存储值。最好可以返回㡳层的错误信息 (或者对用户 或开发者更有用的错误信息) 为何该错误发生，这样可更好让用户/开发者在用我们 API 时自行纠正错误。

我的报错，核心的错误原因是因为提供的 mnemonic 和 用户帐号没对上。

**Comment by AstaFrode** [comment]
Yes, please make sure your account has a balance before registering.

**Comment by AstaFrode** [comment]
Yes, please make sure your account has a balance before registering.
